language: python
dist: trusty
python: 3.6.3
cache:
  timeout: 900
  pip: true
  directories:
    - opencv/
    - opencv_contrib/
before_install:
  - sudo apt-get update
install:
  # OpenCV dependencies - Details available at: http://docs.opencv.org/trunk/doc/tutorials/introduction/linux_install/linux_install.html
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -y python3-numpy

  # Download v3.0.0 .zip file and extract.
  - bash build_opencv.sh

  # Install to OS.
  - cd opencv/build/
  - sudo make install

  # Add configuration to OpenCV to tell it where the library files are located on the file system (/usr/local/lib)
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'

  - sudo ldconfig
  - echo "OpenCV installed."

  - cd ../../

  - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages

  - pip install -r requirements.txt
  - pip install opencv-python
  - pip install flake8
script:
  - flake8 --statistics --show-source --disable-noqa
  - python run.py -i tests/images/goal2016.png
  - python run.py -i tests/images/goal2017.png
